### ISSUE TITLE
x-frame-option sameorigin fails

### ISSUE THREAD

**Issue by rechandler12** [h5bp/server-configs-test#1]
In x-frame-option 2 options are avaliable
- DENY
- SAMEORIGIN

I think tests should pass with SAMEORIGIN too not only with DENY.

**Comment by LeoColomb** [comment]
We test that the target server is the more standard and more secure by default, not the most flexible.
For security, we follow the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege), where `DENY` value is the strictest for `X-Frame-Option`.
